# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wangtao\Desktop\login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(652, 461)
        Dialog.setMinimumSize(QtCore.QSize(652, 461))
        Dialog.setMaximumSize(QtCore.QSize(652, 461))
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(160, 150, 301, 92))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.user = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(12)
        self.user.setFont(font)
        self.user.setObjectName("user")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user)
        self.pwd = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(12)
        self.pwd.setFont(font)
        self.pwd.setObjectName("pwd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pwd)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.loginButton = QtWidgets.QPushButton(Dialog)
        self.loginButton.setGeometry(QtCore.QRect(160, 260, 111, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(12)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.registerButton = QtWidgets.QPushButton(Dialog)
        self.registerButton.setGeometry(QtCore.QRect(360, 260, 101, 28))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(12)
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "账号："))
        self.label_2.setText(_translate("Dialog", "密码:"))
        self.loginButton.setText(_translate("Dialog", "登录"))
        self.registerButton.setText(_translate("Dialog", "注册"))
