# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\wangtao\Desktop\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 683)
        MainWindow.setMinimumSize(QtCore.QSize(915, 683))
        MainWindow.setMaximumSize(QtCore.QSize(915, 683))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(90, 0, 411, 121))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.messageDialog = QtWidgets.QTextBrowser(self.centralwidget)
        self.messageDialog.setGeometry(QtCore.QRect(90, 100, 461, 431))
        self.messageDialog.setObjectName("messageDialog")
        self.userList = QtWidgets.QListView(self.centralwidget)
        self.userList.setGeometry(QtCore.QRect(560, 100, 241, 431))
        self.userList.setObjectName("userList")
        self.messageEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.messageEdit.setGeometry(QtCore.QRect(90, 540, 461, 31))
        self.messageEdit.setObjectName("messageEdit")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(560, 540, 121, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(12)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.sendFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendFileButton.setGeometry(QtCore.QRect(690, 540, 111, 31))
        font = QtGui.QFont()
        font.setFamily("HarmonyOS Sans")
        font.setPointSize(12)
        self.sendFileButton.setFont(font)
        self.sendFileButton.setObjectName("sendFileButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", ""))
        # 在这里将ui逻辑删除
        self.sendButton.setText(_translate("MainWindow", "发送消息"))
        self.sendFileButton.setText(_translate("MainWindow", "发送文件"))
